#!/bin/bash
DIGCUSTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEMPDIR=$DIGCUSTDIR/MoveTemp

mkdir $TEMPDIR
cp $DIGCUSTDIR/checkvrf.awk $TEMPDIR
cp $DIGCUSTDIR/csvgreet $TEMPDIR
cp $DIGCUSTDIR/digCUST $TEMPDIR
cp $DIGCUSTDIR/digCUST.awk $TEMPDIR
cp $DIGCUSTDIR/digCUST.db $TEMPDIR  
cp $DIGCUSTDIR/printgreet.awk $TEMPDIR
cp $DIGCUSTDIR/usagefile $TEMPDIR

$DIGCUSTDIR/checksshkeys.tcl
scp $TEMPDIR/* admin@enterprise-dev.windstream.com:/home/admin/DigCust
scp $TEMPDIR/* admin@enterprise.windstream.com:/home/admin/DigCust
scp $TEMPDIR/* g9983898@ltrkarkvm408:/home/g9983898/Scripts/digCust

rm -r $TEMPDIR
